clone_depth: 5

environment:
  QTDIR: C:\Qt\5.7\msvc2015_64
  GENERATOR: "Visual Studio 14 Win64"

configuration:
  - Release
  - Debug

platform:
  - x64

before_build:
  - 'git submodule update --init --recursive'
  - 'set PATH=%QTDIR%\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%'
  - "sh -c 'pacman -Syu --noconfirm'"
  - 'sh scripts\setup_msys2.sh'
  - mkdir build
  - 'ls C:\msys64\mingw64\lib'
  - cd build
  - cmake "-GNinja" -DCMAKE_BUILD_TYPE="%configuration%" -DCMAKE_PREFIX_PATH="%QTDIR%" -DCG_BUILD_DEBUGGER=OFF ..
  - ninja


#after_build:
#  - SET CTEST_OUTPUT_ON_FAILURE=1
#  - cmake --build . --config %configuration% --target RUN_TESTS || echo "Failed"
